var provinceInfo={};
$(function(){$("#cardNumberInput").bind("keyup",function(){this.value=this.value.replace(/\D/g,"")});""!=$("#cardHolderInput").val()&&""!=$("#IDInput").val()&&($("#cardHolderInput").attr("disabled","disabled"),$("#IDInput").attr("disabled","disabled"));$("#addBank").bind("click",function(){var a=$("#checkNo").val(),c=$("#cardNumberInput").val();if(null==a||""==a)return $(".error").html('<div style="background: url(/statics/images/icon_warn.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">\u9a8c\u8bc1\u7801\u4e3a\u7a7a</div>'),!1;
if(0==$(".icon-click").length)return $(".error").html('<div style="background: url(/statics/images/icon_warn.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">\u8bf7\u540c\u610f\u4e00\u952e\u652f\u4ed8\u534f\u8bae</div>'),!1;$.ajax({type:"POST",url:"/account/card/bindBankCardConfirm",data:{authCode:a,bankCardNo:c},dataType:"json",success:function(a,c){"0000"==a.code?location.href="/account/card":"0003"==a.code?$("#long_warn").html(a.msg):
$(".error").html('<div style="background: url(/statics/images/icon_warn.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">'+a.msg+"</div>")}});return!1});var b=0;$("#checkBank").bind("click",function(){var a=$("#cardNumberInput").val();if(null==a||""==a)return $(".bank_name").html('<div class="error"><div style="background: url(/statics/images/icon_warn.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">\u8bf7\u8f93\u5165\u94f6\u884c\u5361\u53f7</div></div>'),
!1;if(15>a.length)return $(".bank_name").html('<div class="error"><div style="background: url(/statics/images/icon_warn.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u94f6\u884c\u5361\u53f7</div></div>'),!1;0==b&&$.ajax({type:"POST",url:"/account/card/check",data:{bankCardNo:a},dataType:"json",beforeSend:function(){b=1;$(".bank_name").html('<div class="error"><div style="background: url(/statics/images/icon_warn.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">\u6821\u9a8c\u4e2d\u8bf7\u7a0d\u540e...</div></div>')},
success:function(a,d){b=0;"0000"==a.code?($("#bank_id").val(a.bankId),$(".bank_name").html('<div class="pass"><div style="background: url(/statics/images/icon_rec.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">'+a.bankName+"</div></div>"),$("#checkBank").css("display","none"),$("#addBank").css("display","block"),$("#check_suc").css("display","block")):"0003"==a.code?$("#long_warn").html(a.msg):$(".bank_name").html('<div class="error"><div style="background: url(/statics/images/icon_warn.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">'+
a.msg+"</div></div>")},error:function(a,d){b=0}})});var e=60;$(".checkNo").bind("click",function(){if(60>e)return!1;var a=$("#mobile").val(),c=$("#cardHolderInput").val(),d=$("#cardNumberInput").val(),b=$("#bank_id").val(),f=$("#IDInput").val();if(null==a|""==a)return $(".error").html('<div style="background: url(/statics/images/icon_warn.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">\u624b\u673a\u53f7\u4e3a\u7a7a</div>'),!1;if(11>a.length)return $(".error").html('<div style="background: url(/statics/images/icon_warn.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">\u624b\u673a\u53f7\u683c\u5f0f\u6709\u8bef</div>'),
!1;$.ajax({type:"POST",url:"/account/card/sendBindBankCardCode",data:{realName:c,IDCardNo:f,bankId:b,bankCardNo:d,bankTelephone:a},dataType:"json",success:function(a,c){"0000"==a.code?($("#check_no").attr("disabled","true"),$(".error").html(""),$("#mobile").attr("disabled","disabled"),InterValObj=window.setInterval(function(){0==e?(window.clearInterval(InterValObj),$("#check_no").removeAttr("disabled"),$("#check_no").html("\u91cd\u65b0\u53d1\u9001"),$("#check_no").addClass("checkNo"),$("#check_no").css("background",
"#ffa800"),$("#check_no").css("color","#fff"),e=60):(e--,$("#check_no").html("\u91cd\u65b0\u53d1\u9001("+e+")"),$("#check_no").css("background","#eaeaea"),$("#check_no").css("color","#c0c0c0"))},1E3)):"0003"==a.code?$("#long_warn").html(a.msg):$(".error").html('<div style="background: url(/statics/images/icon_warn.png) no-repeat;width:15px;height:15px;position:absolute;margin-top:8px;"></div><div style="margin-left:22px;">'+a.msg+"</div>")}})});$(".rebind_card").bind("click",function(){$("#bankCarkId").val($(this).attr("bankCardNo"));
$("#mobilePhoneId").val($(this).attr("mobilePhone"));$("#rebindForm").submit()});$(".unbind").bind("click",function(){$("#dialog").show();$("#dialog #input").val($(this).attr("bankId"))});$(".unbind1").bind("click",function(){$("#dialog").show();$("#dialog #input").val($(this).attr("bankId"))});$("#dialog .close").bind("click",function(){$("#dialog").hide()});$("#dialog .action a").bind("click",function(){var a=$("#dialog #input").val();$.ajax({type:"POST",url:"/account/card/unbind",data:{bankCardId:a},
dataType:"json",success:function(a,d){$("#dialog").hide();"0000"==a.code&&(location.href="/account/card")}})});$(".support_card").bind("click",function(){$("#dialogBank").show()});$("#dialogBank .close").bind("click",function(){$("#dialogBank").hide()});$(".agree").bind("click",function(){$("#dialogAgreement").show()});$("#dialogAgreement .close").bind("click",function(){$("#dialogAgreement").hide()});$("#cardSelect .selected").bind("change",function(){var a=$(this).find("option:selected").attr("needDetail"),
c=$(this).val();"1"==a?(provinceInfo={},$("#province").show(),$("#region").show(),$("#bankProvince").html('<option value="" disabled selected>\u8bf7\u9009\u62e9</option>'),$("#bankCity").html('<option value="" disabled selected>\u8bf7\u9009\u62e9</option>'),$.ajax({type:"POST",url:"/info/getBankRegion",data:{bankId:c},dataType:"json",success:function(a,c){var f=a.provinceList,b=[];if(void 0!=f&&0<f.length)for(var g=0;g<f.length;g++)provinceInfo[f[g].id]=f[g].cityList,b[b.length]='<option value="'+
f[g].id+'">'+f[g].name+"</option>";$("#bankProvince").append(b.join(""))}})):($("#province").hide(),$("#region").hide(),$("#bankBranchId").val(""))});$("#bankProvince").bind("change",function(){$("#bankCity").html('<option value="" disabled selected>\u8bf7\u9009\u62e9</option>');var a=provinceInfo[$(this).val()],c=[];if(void 0!=a)for(var d=0;d<a.length;d++)c[c.length]='<option value="'+a[d].id+'">'+a[d].name+"</option>";$("#bankCity").append(c.join(""));$("#bankBranchName").removeAttr("readonly");
$("#bankBranchName").val("")});$("#bankBranchName").bind("keyup",function(){$("#regionSelect").show();var a=$(this).val(),c=$("#cardSelect .selected").attr("value"),d=$("#bankProvince").val(),b=$("#bankCity").val();$.ajax({type:"POST",url:"/info/getBankBranch",data:{branchName:a,bankId:c,provinceId:d,cityId:b},dataType:"json",success:function(a,c){var b=a.branchList,d=[];if(void 0!=b&&0<b.length)for(var e=0;e<b.length;e++)d[d.length]='<li id="'+b[e].id+'">'+b[e].name+"</li>";$("#regionSelect").html(d.join(""));
$("#regionSelect li").bind("click",function(){$("#bankBranchName").val($(this).html());$("#bankBranchId").val($(this).attr("id"));$("#regionSelect").hide()})}})}).bind("focusout",function(){setTimeout(function(){$("#regionSelect").hide()},1E3)});$(".select-control").bind("click",function(a){a.stopPropagation();"none"==$("#bankList").css("display")?$("#bankList").css("display","block"):$("#bankList").css("display","none")});$(document.body).bind("click",function(){$("#bankList").css("display","none")});
$("#bankList .bank").bind("mouseover",function(){$(this).addClass("bank-check")}).bind("mouseout",function(){$(this).removeClass("bank-check")}).bind("click",function(){$("#cardSelect .selected").addClass("input");$("#cardSelect .selected").html($(this).html());$("#cardSelect .selected").attr("value",$(this).attr("value"));$("#cardSelect .selected").attr("needDetail",$(this).attr("needDetail"));$(this).parent().css("display","none")})});
