var realPrice;
$(function(){function f(a){$.post("/info/getGoldPrice",{queryFlag:a},function(b){if(b.success){var c=1,d=[],e=b.priceArray;2==a?c=4:0==a&&(c=5);for(b=0;b<e.length;b++)d[b]=parseFloat(e[b].y);$("#graph").highcharts({chart:{type:"spline"},title:{text:""},yAxis:{title:null},colors:["#ff9f10"],exporting:!1,xAxis:{labels:{formatter:function(){var b=(new Date(e[this.value].x)).format("yyyy-MM-dd hh:mm");return"2"==a?b.substring(11,13):b.substring(8,10)}},title:{enabled:!0},tickWidth:0,tickInterval:c},tooltip:{formatter:function(){var a=
'<b style="font-family:Helvetica;font-size:14px;color:'+this.series.color+'">'+this.y+"\u5143/\u514b</b><br/>";return a+='<span style="font-size: 14px;color:#a3a3a3;font-family:Helvetica;">'+(new Date(e[this.x].x)).format("yyyy-MM-dd hh:mm")+"</span>"}},series:[{name:"\u91d1\u4ef7",data:d}],legend:!1,plotOptions:{spline:{marker:{enabled:!1}}},credits:!1})}})}var d=null;$(".icon-weixin").bind("mouseover",function(a){clearTimeout(d);$(".ceil-weixin").show();return!1}).bind("mouseout",function(){clearTimeout(d);
d=setTimeout(function(){$(".ceil-weixin").hide()},500)});$(".ceil-weixin").bind("mouseover",function(a){clearTimeout(d);$(".ceil-weixin").show()}).bind("mouseout",function(){clearTimeout(d);d=setTimeout(function(){$(".ceil-weixin").hide()},500)});$(".footer_wx,.ceil-weixin-bottom").bind("mouseover",function(a){clearTimeout(d);$(".ceil-weixin-bottom").show()}).bind("mouseout",function(){clearTimeout(d);d=setTimeout(function(){$(".ceil-weixin-bottom").hide()},500)});$(".ceil-weixin-bottom").bind("mouseover",
function(a){clearTimeout(d);$(".ceil-weixin-bottom").show()}).bind("mouseout",function(){clearTimeout(d);d=setTimeout(function(){$(".ceil-weixin-bottom").hide()},500)});var c=null;$(".download_client,#span1").bind("mouseover",function(a){clearTimeout(c);$(".gw-code-win2").show();return!1}).bind("mouseout",function(){clearTimeout(c);c=setTimeout(function(){$(".gw-code-win2").hide()},500)});$(".gw-code-win2").bind("mouseover",function(a){clearTimeout(c);$(".gw-code-win2").show()}).bind("mouseout",function(){clearTimeout(c);
c=setTimeout(function(){$(".gw-code-win2").hide()},500)});c=null;$(".gw-picture").bind("mouseover",function(a){clearTimeout(c);$(".gw-code-win").show();return!1}).bind("mouseout",function(){clearTimeout(c);c=setTimeout(function(){$(".gw-code-win").hide()},500)});$(".gw-code-win").bind("mouseover",function(a){clearTimeout(c);$(".gw-code-win").show()}).bind("mouseout",function(){clearTimeout(c);c=setTimeout(function(){$(".gw-code-win").hide()},500)});$.ajax({type:"POST",url:"/info/price",dataType:"json",
success:function(a,b){"ok"==a.status&&(realPrice=a.price,$(".price-update #first").html(parseInt(realPrice/100)),10>parseInt(realPrice%100)?$(".price-update #second").html("0"+parseInt(realPrice%100)):$(".price-update #second").html(parseInt(realPrice%100)),$(".price-update .number").html((realPrice/100).toFixed(2)))}});setInterval(function(){$.ajax({type:"POST",url:"/info/price",dataType:"json",success:function(a,b){"ok"==a.status&&(realPrice=a.price,$(".price-update #first").html(parseInt(realPrice/
100)),10>parseInt(realPrice%100)?$(".price-update #second").html("0"+parseInt(realPrice%100)):$(".price-update #second").html(parseInt(realPrice%100)),$(".price-update .number").html((realPrice/100).toFixed(2)))}})},6E4);Date.prototype.format=function(a){var b={"M+":this.getMonth()+1,"d+":this.getDate(),"h+":this.getHours(),"m+":this.getMinutes(),"s+":this.getSeconds(),"q+":Math.floor((this.getMonth()+3)/3),S:this.getMilliseconds()};/(y+)/.test(a)&&(a=a.replace(RegExp.$1,(this.getFullYear()+"").substr(4-
RegExp.$1.length)));for(var c in b)(new RegExp("("+c+")")).test(a)&&(a=a.replace(RegExp.$1,1==RegExp.$1.length?b[c]:("00"+b[c]).substr((""+b[c]).length)));return a};$(document).ajaxSuccess(function(a,b){b.responseJSON&&"0002"===b.responseJSON.code?location.href="/user/login":b.responseJSON&&"0110"===b.responseJSON.code&&alert("\u60a8\u7684\u64cd\u4f5c\u8fc7\u4e8e\u9891\u7e41\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5")});0<$("#graph").length&&f("0");$(".graphs-tab li").click(function(){var a=$(this);$(this).parent().find("li").removeClass("active");
a.addClass("active");f(a.attr("name"));"2"==a.attr("name")?$(".graphs-tab-up1").css("left","63px"):"1"==a.attr("name")?$(".graphs-tab-up1").css("left","211px"):"0"==a.attr("name")&&$(".graphs-tab-up1").css("left","359px")});$(".button-1").bind("mousedown",function(){$(this).css("background","url(/statics/images/account_button1_press.png) no-repeat")}).bind("mouseup",function(){$(this).css("background","url(/statics/images/account_button1.png) no-repeat")});setInterval(function(){var a=document.documentElement.clientHeight||
document.body.clientHeight,b=document.body.scrollTop||document.documentElement.scrollTop,c=$(".footer_wx").offset().top;223>a-(c-b)?$(".ceil-weixin-bottom").addClass("footer_wxUp"):$(".ceil-weixin-bottom").removeClass("footer_wxUp")},30)});
